### ISSUE TITLE
Couldn't find the path fabric-samples/chaincode

### ISSUE THREAD

**Issue by sreenivasmalae** [alfahami/bcertificate#1]
In fabric-samples there is no folder name chaincode 

Can you tell us exactly which fabric_version and fabric-ca_version were used in the project.

That will helps us to build the project

**Comment by alfahami** [comment]
Hello,

I'll upload the fabric-samples folder as well, I've seen that Hyperledger
has changed their original folder structure.

Regards,
Toihir

**Comment by sreenivasmalae** [comment]
Hi @alfahami 

Thank you so much for the update
Also, can you please help me with the below command
Copy this file (test-network/add_path_org1.sh) to certficate-network/test-network

Can you please provide the full path of test-network/add_path_org1.sh
Because i don't see the add_path_org1.sh file in fabric samples 

In bCertificate/certficate-network/test-network the file is already available

**Comment by alfahami** [comment]
You're welcome the add_path_org1.sh was created by me in order to make some kind of automation.
I'll look it up and upload it.

**Comment by alfahami** [comment]
Hi @sreenivasmalae, 
You're welcome.

The add_path_org1.sh was not downloaded with the original fabric-samples, I created it in order to make some kind of automation. 
I'll look it up and upload it, once found.

**Comment by alfahami** [comment]
Hi @alfahami I added the script and updated the README, please take a look and let me know.
